"""Report generation: PDF (ReportLab), Excel (OpenPyXL), CSV and PowerPoint."""
from __future__ import annotations
import io
import re
from datetime import datetime

import pandas as pd
from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer, Table,
                                TableStyle, Image, PageBreak)

from .config import APP_NAME, REPORT_DIR
from .kpis import compute, format_kpi

ACCENT = colors.HexColor("#3B5BDB")
DARK = colors.HexColor("#111827")
MUTED = colors.HexColor("#6B7280")
LIGHT = colors.HexColor("#F3F4F6")


def _styles():
    ss = getSampleStyleSheet()
    ss.add(ParagraphStyle("H1x", parent=ss["Heading1"], textColor=DARK, fontSize=20,
                          spaceAfter=4, leading=24))
    ss.add(ParagraphStyle("H2x", parent=ss["Heading2"], textColor=ACCENT, fontSize=13,
                          spaceBefore=12, spaceAfter=6))
    ss.add(ParagraphStyle("Bodyx", parent=ss["BodyText"], fontSize=9.5, leading=14,
                          textColor=DARK, alignment=TA_LEFT))
    ss.add(ParagraphStyle("Mutedx", parent=ss["BodyText"], fontSize=8.5, textColor=MUTED))
    ss.add(ParagraphStyle("Bulletx", parent=ss["BodyText"], fontSize=9.5, leading=14,
                          leftIndent=10, bulletIndent=2, textColor=DARK))
    return ss


def _md_clean(text: str) -> str:
    text = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", text)
    text = re.sub(r"`(.+?)`", r"<font face='Courier'>\1</font>", text)
    return text.replace("&", "&amp;").replace("<b>", "\x00b\x01").replace("</b>", "\x00/b\x01") \
               .replace("<", "&lt;").replace(">", "&gt;") \
               .replace("\x00b\x01", "<b>").replace("\x00/b\x01", "</b>")


def _kpi_table(kpis: dict):
    rows, row = [], []
    for name, v in kpis.items():
        if v["value"] is None:
            continue
        delta = f"  ({v['delta']:+.1f}%)" if v["delta"] is not None else ""
        row.append(Paragraph(f"<b>{format_kpi(name, v['value'])}</b>{delta}<br/>"
                             f"<font size=7.5 color='#6B7280'>{name.upper()}</font>",
                             _styles()["Bodyx"]))
        if len(row) == 4:
            rows.append(row)
            row = []
    if row:
        row += [""] * (4 - len(row))
        rows.append(row)
    if not rows:
        return None
    t = Table(rows, colWidths=[43 * mm] * 4)
    t.setStyle(TableStyle([
        ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#E5E7EB")),
        ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E5E7EB")),
        ("BACKGROUND", (0, 0), (-1, -1), LIGHT),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 8), ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
    ]))
    return t


def df_to_table(df: pd.DataFrame, max_rows=18, col_width=None):
    d = df.head(max_rows).copy()
    for c in d.columns:
        if pd.api.types.is_float_dtype(d[c]):
            d[c] = d[c].round(2)
    data = [[str(c)[:22] for c in d.columns]] + [[str(v)[:28] for v in r] for r in d.values]
    n = len(d.columns)
    t = Table(data, colWidths=col_width or [(175 / max(n, 1)) * mm] * n, repeatRows=1)
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), ACCENT),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTSIZE", (0, 0), (-1, -1), 7.5),
        ("GRID", (0, 0), (-1, -1), 0.35, colors.HexColor("#E5E7EB")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT]),
        ("TOPPADDING", (0, 0), (-1, -1), 4), ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    return t


def fig_to_png(fig, width=1000, height=430) -> bytes | None:
    """Requires kaleido; returns None if unavailable so PDFs still build."""
    try:
        return fig.to_image(format="png", width=width, height=height, scale=2)
    except Exception:
        return None


def build_pdf(df: pd.DataFrame, mapping: dict, title="Business Performance Report",
              insights_md: str = "", tables: dict | None = None,
              figures: list | None = None, author="AI Business Analytics Studio") -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, leftMargin=18 * mm, rightMargin=18 * mm,
                            topMargin=18 * mm, bottomMargin=16 * mm, title=title, author=author)
    ss = _styles()
    story = [Paragraph(title, ss["H1x"]),
             Paragraph(f"Generated by {APP_NAME} &nbsp;•&nbsp; "
                       f"{datetime.now():%d %B %Y, %H:%M} &nbsp;•&nbsp; "
                       f"{len(df):,} records analysed", ss["Mutedx"]),
             Spacer(1, 10)]

    story.append(Paragraph("Key Performance Indicators", ss["H2x"]))
    kt = _kpi_table(compute(df, mapping))
    if kt:
        story.append(kt)
    story.append(Spacer(1, 8))

    for fig in (figures or []):
        png = fig_to_png(fig)
        if png:
            story.append(Image(io.BytesIO(png), width=175 * mm, height=75 * mm))
            story.append(Spacer(1, 8))

    if insights_md:
        story.append(Paragraph("AI-Generated Business Insights", ss["H2x"]))
        for line in insights_md.splitlines():
            s = line.strip()
            if not s:
                continue
            if s.startswith("## "):
                story.append(Paragraph(_md_clean(s[3:]), ss["H2x"]))
            elif s.startswith(("- ", "* ")):
                story.append(Paragraph(_md_clean(s[2:]), ss["Bulletx"], bulletText="•"))
            elif s.startswith("#"):
                story.append(Paragraph(_md_clean(s.lstrip("# ")), ss["H2x"]))
            else:
                story.append(Paragraph(_md_clean(s), ss["Bodyx"]))

    for name, table_df in (tables or {}).items():
        if table_df is None or getattr(table_df, "empty", True):
            continue
        story.append(PageBreak())
        story.append(Paragraph(name, ss["H2x"]))
        story.append(df_to_table(table_df))

    def footer(canvas, doc_):
        canvas.saveState()
        canvas.setFont("Helvetica", 7.5)
        canvas.setFillColor(MUTED)
        canvas.drawString(18 * mm, 10 * mm, f"{APP_NAME} — confidential")
        canvas.drawRightString(A4[0] - 18 * mm, 10 * mm, f"Page {doc_.page}")
        canvas.restoreState()

    doc.build(story, onFirstPage=footer, onLaterPages=footer)
    return buf.getvalue()


def build_excel(sheets: dict[str, pd.DataFrame], kpis: dict | None = None) -> bytes:
    buf = io.BytesIO()
    with pd.ExcelWriter(buf, engine="openpyxl") as xl:
        if kpis:
            pd.DataFrame([{"KPI": k, "Value": format_kpi(k, v["value"]),
                           "Change %": round(v["delta"], 2) if v["delta"] is not None else None}
                          for k, v in kpis.items() if v["value"] is not None]) \
                .to_excel(xl, sheet_name="KPIs", index=False)
        for name, d in sheets.items():
            if d is None or getattr(d, "empty", True):
                continue
            d.head(100_000).to_excel(xl, sheet_name=str(name)[:31], index=False)

        from openpyxl.styles import Font, PatternFill, Alignment
        head_fill = PatternFill("solid", start_color="3B5BDB")
        for ws in xl.book.worksheets:
            for c in ws[1]:
                c.font = Font(bold=True, color="FFFFFF")
                c.fill = head_fill
                c.alignment = Alignment(vertical="center")
            ws.freeze_panes = "A2"
            for col in ws.columns:
                width = max((len(str(c.value)) for c in col if c.value is not None), default=8)
                ws.column_dimensions[col[0].column_letter].width = min(max(width + 3, 11), 42)
    return buf.getvalue()


def build_pptx(title: str, kpis: dict, insights_md: str, figures: list | None = None) -> bytes | None:
    try:
        from pptx import Presentation
        from pptx.util import Inches, Pt
        from pptx.dml.color import RGBColor
    except Exception:
        return None

    prs = Presentation()
    prs.slide_width, prs.slide_height = Inches(13.333), Inches(7.5)

    s = prs.slides.add_slide(prs.slide_layouts[6])
    tb = s.shapes.add_textbox(Inches(0.8), Inches(2.4), Inches(11), Inches(2))
    p = tb.text_frame.paragraphs[0]
    p.text = title
    p.font.size, p.font.bold = Pt(42), True
    p.font.color.rgb = RGBColor(0x11, 0x18, 0x27)
    p2 = tb.text_frame.add_paragraph()
    p2.text = f"{APP_NAME} · {datetime.now():%d %B %Y}"
    p2.font.size, p2.font.color.rgb = Pt(16), RGBColor(0x6B, 0x72, 0x80)

    s = prs.slides.add_slide(prs.slide_layouts[5])
    s.shapes.title.text = "Key Performance Indicators"
    body = s.shapes.add_textbox(Inches(0.8), Inches(1.7), Inches(11.5), Inches(5)).text_frame
    for k, v in kpis.items():
        if v["value"] is None:
            continue
        par = body.add_paragraph()
        delta = f"  ({v['delta']:+.1f}%)" if v["delta"] is not None else ""
        par.text = f"{k}: {format_kpi(k, v['value'])}{delta}"
        par.font.size = Pt(18)

    section, bullets = None, []

    def flush():
        if not section:
            return
        sl = prs.slides.add_slide(prs.slide_layouts[5])
        sl.shapes.title.text = section
        tf = sl.shapes.add_textbox(Inches(0.8), Inches(1.7), Inches(11.5), Inches(5)).text_frame
        tf.word_wrap = True
        for b in bullets[:6]:
            par = tf.add_paragraph()
            par.text = "• " + re.sub(r"\*\*(.+?)\*\*", r"\1", b)
            par.font.size = Pt(16)

    for line in (insights_md or "").splitlines():
        s_ = line.strip()
        if s_.startswith("## "):
            flush()
            section, bullets = s_[3:], []
        elif s_.startswith(("- ", "* ")):
            bullets.append(s_[2:])
    flush()

    buf = io.BytesIO()
    prs.save(buf)
    return buf.getvalue()


def save(content: bytes, filename: str) -> str:
    path = REPORT_DIR / filename
    path.write_bytes(content)
    return str(path)
